baseURL = "https://robertwenink.xyz"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Robert Wenink"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "I'm a geit"
author = "Gerry Geit"
description = "Call me Geitty"
profilePicture = "images/geit.png"
keywords = ""
favicon = "favicons/"
customCss = []

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/robertwenink"

#[[params.socialIcons]]
#icon = "fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:R.C.T.Wenink@student.tudelft.nl"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

