baseURL = "https://robertwenink.xyz/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Home"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = ""
author = "Robert Wenink"
description = "Student Computer Scientist & Marine Engineering"
profilePicture = "images/pf.jfif"
keywords = ""
favicon = "favicons/"
customCss = ["css/added_style.css"]
introtext = "Welcome to this website dedicated to keeping track of my adventures in the combined and somewhat suprising field of Computer Science and Marine Engineering. Feel free to browse some."

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/robertwenink/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/robertwenink"

#[[params.socialIcons]]
#icon = "fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:R.C.T.Wenink@student.tudelft.nl"

## Menu items

[taxonomies]
	tag = "tags"
	category = "categories"
	field = "field"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

