[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.115.4"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.115.4"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.115.4"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.115.4"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/about/"
  to = "https://www.robertwenink.com/about/"
  force = true

[[redirects]]
  from = "/resume/"
  to = "https://www.robertwenink.com/resume/"
  force = true

[[redirects]]
  from = "/projects/*"
  to = "https://www.robertwenink.com/projects/"
  force = true

[[redirects]]
  from = "/posts/*"
  to = "https://www.robertwenink.com/posts/"
  force = true

[[redirects]]
  from = "/*"
  to = "https://www.robertwenink.com"
  force = true # COMMENT: ensure that we always redirect
